### ISSUE TITLE
Error in the second step pipeline while running motus-extender.py

### ISSUE THREAD

**Issue by Ye-Ling1108** [motu-tool/mOTUs-extender#1] opened 2022-10-31 14:07 UTC
When I running motus-extender.py, the second step pipeline shown error. But I haven't had a chance to dig into what might be going wrong yet, I hope to help! from you soon.
///
Error in rule prodigalfetchMgs:
    jobid: 40
    output: mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/GCA_903928895.1.prodigal_fetchMGs.done
    log: mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/GCA_903928895.1.prodigal_fetchMGs.log, mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/GCA_903928895.1.prodigal_fetchMGs.command (check log file(s) for error message)
    shell:
        
        rm -rf mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/*
        rm -rf mOTUs-extender/test_extension/extension/extension/dbs/GCA_903928895.1
        command="

        mkdir -p mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/genome/
        mkdir -p mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/
        mkdir -p mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/
        rsync mOTUs-extender/test_extension/genomes/GCA_903928895.1.fa mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/genome/
       	prodigal -i mOTUs-extender/test_extension/genomes/GCA_903928895.1.fa -a mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/GCA_903928895.1.faa -d mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/GCA_903928895.1.fna -f gff -o mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/GCA_903928895.1.gff -c -m -g 11 -p single
        rm -rf mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs/
        fetchMGs.pl -m extraction -v -i -d mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/GCA_903928895.1.fna -o mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs/ mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/prodigal/GCA_903928895.1.faa -t 1
        mkdir -p mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs-renamed/
        python mOTUs-extender/mOTUs-extender//parse_fetchMGs.py mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs/ mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs-renamed/ GCA_903928895.1
        rm -r mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs/hmmResults/
        rm -r mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs/temp/
        if [ -f mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs-renamed/motus.mgs.count.ok ]; then
            sh mOTUs-extender//extend_mOTUs_addMarkerGenes.sh mOTUs-extender/test_extension/genomes/GCA_903928895.1.fa GCA_903928895.1 mOTUs-extender/test_extension/extension/extension/ mOTUs-extender/ mOTUs-extender/test_extension/extension/temp_db_folder/ mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/fetchMGs/GCA_903928895.1-bestMGs-renamed/ mOTUs-extender/test_extension/extension/mOTU.v3.0.mOTU-LG.map
        fi
        
        ";
        echo "$command" > mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/GCA_903928895.1.prodigal_fetchMGs.command;
        eval "$command" &> mOTUs-extender/test_extension/extension/genes/GCA_903928895.1/GCA_903928895.1.prodigal_fetchMGs.log
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
///

**Comment by hjruscheweyh** [comment] 2022-10-31 16:04
HI @Ye-Ling1108 

can you share the content of the  `GCA_903928895.1.prodigal_fetchMGs.log` file? 

You should be able to rerun the same script and it will be executed on the missing genomes only. 

Best,
Hans

**Comment by Ye-Ling1108** [comment] 2022-11-01 00:13
@hjruscheweyh 
Thank you very much for your answer. 
This is the GCA_903928895.1.prodigal_fetchMGs.log file:
[GCA_903928895.1.prodigal_fetchMGs.log](https://github.com/motu-tool/mOTUs-extender/files/9905695/GCA_903928895.1.prodigal_fetchMGs.log)

**Comment by hjruscheweyh** [comment] 2022-11-01 07:57
Hi @Ye-Ling1108 

The issue seems to be that your system doesn't have `bash` as default shell. Can it be that you're on ubuntu or MacOS?

Can you try to add `#!/bin/bash` to the top of this script: `mOTUs-extender/mOTUs-extender//extend_mOTUs_addMarkerGenes.sh` and rerun the command?


Let me know if that fixes this part of the pipeline. I will then update the code.

Hans

**Comment by Ye-Ling1108** [comment] 2022-11-01 08:50
@hjruscheweyh I ran the pipeline on Linux, but it still doesn't work.
[GCA_903928895.1.prodigal_fetchMGs.log](https://github.com/motu-tool/mOTUs-extender/files/9908278/GCA_903928895.1.prodigal_fetchMGs.log)

**Comment by hjruscheweyh** [comment] 2022-11-03 16:05
Are you sure that you have added the `#!/bin/bash` flag to the beginning of `extend_mOTUs_addMarkerGenes.sh`? There was no other error?

**Comment by Ye-Ling1108** [comment] 2022-11-04 02:08
Yes, I did add #!/bin/bash. It reported the same error when I ran. I have enclosed the log and extend_mOTUs_addMarkerGenes.sh files and please have a look. Thank a lot.
///extend_mOTUs_addMarkerGenes.sh file
[extend_mOTUs_addMarkerGenes.txt](https://github.com/motu-tool/mOTUs-extender/files/9934213/extend_mOTUs_addMarkerGenes.txt)
///
[GCA_903928895.1.prodigal_fetchMGs.log](https://github.com/motu-tool/mOTUs-extender/files/9935134/GCA_903928895.1.prodigal_fetchMGs.log)
///
Best

**Comment by Ye-Ling1108** [comment] 2022-11-09 01:16
Hello, 
Thanks for the reply!
has this issue been solved, or is there some other issue you might suspect? 
Best.

**Comment by hjruscheweyh** [comment] 2022-11-10 13:08
Hello

I have been trying to reproduce the error. I have found only one reason that can cause this output and that is that your default shell is not bash. I thought this should be fixed by updating the shebang. Can you please send me the exact version/distribution of your linux by executing the following command?

```
hostnamectl
```

Can you please also send the output this command produces?


```
echo $0
```

and

```
bash --version
```

**Comment by Ye-Ling1108** [comment] 2022-11-10 13:25
Thanks for the reply! OK. 
This my Linux version/distribution and bash version:

> ```
> hostnamectl
> ```
>   Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-42-generic
      Architecture: x86-64

> ```
> echo $0
> ```
> -bash

> ```
> bash --version
> ```
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Best.

**Comment by hjruscheweyh** [comment] 2022-11-15 07:30
Good Morning

Im trying to run the extender in an ubuntu VM. This will take a few more days. I will report back once I have results.

Hans

**Comment by Ye-Ling1108** [comment] 2022-11-16 00:33
ok, thank you very much for your reply.
Best.

**Comment by hjruscheweyh** [comment] 2022-12-06 13:49
Hi @Ye-Ling1108 
I see a similar issue when using Ubuntu. There might be 2 ways of fixing:

1. replace the `sh` with `bash` here: https://github.com/motu-tool/mOTUs-extender/blob/4f09451fcb257351328b71b76ff8a17c8fd60260/mOTUs-extender/0prod_fetchMGs.py#L72
2. or remove the first line in https://github.com/motu-tool/mOTUs-extender/blob/4f09451fcb257351328b71b76ff8a17c8fd60260/mOTUs-extender/extend_mOTUs_addMarkerGenes.sh#L1 . We will fix this issue with the next version.

Please check the fixes and let us know.

Best,
hans

**Comment by Ye-Ling1108** [comment] 2022-12-07 01:04
> ok, thank you very much for your reply, I will try the 2 ways you provided.
Best

**Comment by Ye-Ling1108** [comment] 2022-12-11 11:47
Hello,
Thank you very your suggestion.
I tried to run the extender using the 2 ways you provided. The 3 step pipeline will be running ok.
Best.

**Comment by hjruscheweyh** [comment] 2023-05-12 05:59
The safe mode was disabled in dd15f79bb95a118162a4e247a7c8689bd2f90e93 which enables Ubuntu users to also extend their databases.

**Closed as completed by hjruscheweyh** 2023-05-12 05:59 UTC
Labels: question
